### ISSUE TITLE
[Test] Checklist of tests to be run before 1.0.0 release

### ISSUE THREAD

**Issue by thomasgalliker** [thomasgalliker/CameraScanner.Maui#5]
- [x] Test on iOS simulator
- [x] Test on Android emulator
- [x] Test on iOS devices incl. iOS 12.x
- [x] Test on Android devices
- [x] Cleanup TODOs
- [x] Create list of test barcodes and scan them under controlled/defined conditions
